WITH perf_wide AS (          -- 1 row per loan; this CTE == all 82 bank joins
    SELECT distinct_loan_no,
        SUM(CASE WHEN mob=0 THEN amt_90plus_settlement END) AS bad_0,
        SUM(CASE WHEN mob=0 THEN tpos END)                  AS tpos_0,
        SUM(CASE WHEN mob=3 THEN amt_90plus_settlement END) AS bad_3,
        SUM(CASE WHEN mob=3 THEN tpos END)                  AS tpos_3,
        SUM(CASE WHEN mob=6 THEN amt_90plus_settlement END) AS bad_6,
        SUM(CASE WHEN mob=6 THEN tpos END)                  AS tpos_6,
        SUM(CASE WHEN mob=9 THEN amt_90plus_settlement END) AS bad_9,
        SUM(CASE WHEN mob=9 THEN tpos END)                  AS tpos_9,
        SUM(CASE WHEN mob=12 THEN amt_90plus_settlement END) AS bad_12,
        SUM(CASE WHEN mob=12 THEN tpos END)                  AS tpos_12,
        SUM(CASE WHEN mob=15 THEN amt_90plus_settlement END) AS bad_15,
        SUM(CASE WHEN mob=15 THEN tpos END)                  AS tpos_15,
        SUM(CASE WHEN mob=18 THEN amt_90plus_settlement END) AS bad_18,
        SUM(CASE WHEN mob=18 THEN tpos END)                  AS tpos_18,
        SUM(CASE WHEN mob=21 THEN amt_90plus_settlement END) AS bad_21,
        SUM(CASE WHEN mob=21 THEN tpos END)                  AS tpos_21,
        SUM(CASE WHEN mob=24 THEN amt_90plus_settlement END) AS bad_24,
        SUM(CASE WHEN mob=24 THEN tpos END)                  AS tpos_24,
        SUM(CASE WHEN mob=27 THEN amt_90plus_settlement END) AS bad_27,
        SUM(CASE WHEN mob=27 THEN tpos END)                  AS tpos_27,
        SUM(CASE WHEN mob=30 THEN amt_90plus_settlement END) AS bad_30,
        SUM(CASE WHEN mob=30 THEN tpos END)                  AS tpos_30,
        SUM(CASE WHEN mob=33 THEN amt_90plus_settlement END) AS bad_33,
        SUM(CASE WHEN mob=33 THEN tpos END)                  AS tpos_33,
        SUM(CASE WHEN mob=36 THEN amt_90plus_settlement END) AS bad_36,
        SUM(CASE WHEN mob=36 THEN tpos END)                  AS tpos_36,
        SUM(CASE WHEN mob=39 THEN amt_90plus_settlement END) AS bad_39,
        SUM(CASE WHEN mob=39 THEN tpos END)                  AS tpos_39,
        SUM(CASE WHEN mob=42 THEN amt_90plus_settlement END) AS bad_42,
        SUM(CASE WHEN mob=42 THEN tpos END)                  AS tpos_42,
        SUM(CASE WHEN mob=45 THEN amt_90plus_settlement END) AS bad_45,
        SUM(CASE WHEN mob=45 THEN tpos END)                  AS tpos_45,
        SUM(CASE WHEN mob=48 THEN amt_90plus_settlement END) AS bad_48,
        SUM(CASE WHEN mob=48 THEN tpos END)                  AS tpos_48,
        SUM(CASE WHEN mob=51 THEN amt_90plus_settlement END) AS bad_51,
        SUM(CASE WHEN mob=51 THEN tpos END)                  AS tpos_51,
        SUM(CASE WHEN mob=54 THEN amt_90plus_settlement END) AS bad_54,
        SUM(CASE WHEN mob=54 THEN tpos END)                  AS tpos_54,
        SUM(CASE WHEN mob=57 THEN amt_90plus_settlement END) AS bad_57,
        SUM(CASE WHEN mob=57 THEN tpos END)                  AS tpos_57,
        SUM(CASE WHEN mob=60 THEN amt_90plus_settlement END) AS bad_60,
        SUM(CASE WHEN mob=60 THEN tpos END)                  AS tpos_60,
        SUM(CASE WHEN mob=63 THEN amt_90plus_settlement END) AS bad_63,
        SUM(CASE WHEN mob=63 THEN tpos END)                  AS tpos_63,
        SUM(CASE WHEN mob=66 THEN amt_90plus_settlement END) AS bad_66,
        SUM(CASE WHEN mob=66 THEN tpos END)                  AS tpos_66,
        SUM(CASE WHEN mob=69 THEN amt_90plus_settlement END) AS bad_69,
        SUM(CASE WHEN mob=69 THEN tpos END)                  AS tpos_69,
        SUM(CASE WHEN mob=72 THEN amt_90plus_settlement END) AS bad_72,
        SUM(CASE WHEN mob=72 THEN tpos END)                  AS tpos_72,
        SUM(CASE WHEN mob=75 THEN amt_90plus_settlement END) AS bad_75,
        SUM(CASE WHEN mob=75 THEN tpos END)                  AS tpos_75,
        SUM(CASE WHEN mob=78 THEN amt_90plus_settlement END) AS bad_78,
        SUM(CASE WHEN mob=78 THEN tpos END)                  AS tpos_78,
        SUM(CASE WHEN mob=81 THEN amt_90plus_settlement END) AS bad_81,
        SUM(CASE WHEN mob=81 THEN tpos END)                  AS tpos_81,
        SUM(CASE WHEN mob=84 THEN amt_90plus_settlement END) AS bad_84,
        SUM(CASE WHEN mob=84 THEN tpos END)                  AS tpos_84,
        SUM(CASE WHEN mob=87 THEN amt_90plus_settlement END) AS bad_87,
        SUM(CASE WHEN mob=87 THEN tpos END)                  AS tpos_87,
        SUM(CASE WHEN mob=90 THEN amt_90plus_settlement END) AS bad_90,
        SUM(CASE WHEN mob=90 THEN tpos END)                  AS tpos_90,
        SUM(CASE WHEN mob=93 THEN amt_90plus_settlement END) AS bad_93,
        SUM(CASE WHEN mob=93 THEN tpos END)                  AS tpos_93,
        SUM(CASE WHEN mob=96 THEN amt_90plus_settlement END) AS bad_96,
        SUM(CASE WHEN mob=96 THEN tpos END)                  AS tpos_96,
        SUM(CASE WHEN mob=99 THEN amt_90plus_settlement END) AS bad_99,
        SUM(CASE WHEN mob=99 THEN tpos END)                  AS tpos_99,
        SUM(CASE WHEN mob=102 THEN amt_90plus_settlement END) AS bad_102,
        SUM(CASE WHEN mob=102 THEN tpos END)                  AS tpos_102,
        SUM(CASE WHEN mob=105 THEN amt_90plus_settlement END) AS bad_105,
        SUM(CASE WHEN mob=105 THEN tpos END)                  AS tpos_105,
        SUM(CASE WHEN mob=108 THEN amt_90plus_settlement END) AS bad_108,
        SUM(CASE WHEN mob=108 THEN tpos END)                  AS tpos_108,
        SUM(CASE WHEN mob=111 THEN amt_90plus_settlement END) AS bad_111,
        SUM(CASE WHEN mob=111 THEN tpos END)                  AS tpos_111,
        SUM(CASE WHEN mob=114 THEN amt_90plus_settlement END) AS bad_114,
        SUM(CASE WHEN mob=114 THEN tpos END)                  AS tpos_114,
        SUM(CASE WHEN mob=117 THEN amt_90plus_settlement END) AS bad_117,
        SUM(CASE WHEN mob=117 THEN tpos END)                  AS tpos_117,
        SUM(CASE WHEN mob=120 THEN amt_90plus_settlement END) AS bad_120,
        SUM(CASE WHEN mob=120 THEN tpos END)                  AS tpos_120
    FROM performance
    GROUP BY distinct_loan_no
),
base_fy AS (                 -- filter window + derive FY quarter in SQL
    SELECT distinct_loan_no, segment, disbursal_amount,
           'FY' ||
    substr(CAST(CASE WHEN CAST(strftime('%m', disbursal_date) AS INT) IN (1,2,3)
                     THEN strftime('%Y', disbursal_date)
                     ELSE strftime('%Y', disbursal_date) + 1 END AS TEXT), 3, 2)
    || '-Q' ||
    CASE WHEN CAST(strftime('%m', disbursal_date) AS INT) IN (4,5,6)   THEN 1
         WHEN CAST(strftime('%m', disbursal_date) AS INT) IN (7,8,9)   THEN 2
         WHEN CAST(strftime('%m', disbursal_date) AS INT) IN (10,11,12) THEN 3
         ELSE 4 END AS fy_quarter
    FROM base_loans
    WHERE disbursal_date >= ? AND disbursal_date <= ?
)
SELECT
    b.fy_quarter                       AS FY_QUARTER,
    b.segment                          AS SEGMENT,
    COUNT(*)                           AS LAN_CNT,
    ROUND(SUM(b.disbursal_amount)/1e7, 6) AS DISBURSAL_AMT,
    ROUND(SUM(pw.bad_0)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_0MOB,
    ROUND(SUM(pw.bad_3)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_3MOB,
    ROUND(SUM(pw.bad_6)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_6MOB,
    ROUND(SUM(pw.bad_9)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_9MOB,
    ROUND(SUM(pw.bad_12)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_12MOB,
    ROUND(SUM(pw.bad_15)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_15MOB,
    ROUND(SUM(pw.bad_18)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_18MOB,
    ROUND(SUM(pw.bad_21)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_21MOB,
    ROUND(SUM(pw.bad_24)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_24MOB,
    ROUND(SUM(pw.bad_27)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_27MOB,
    ROUND(SUM(pw.bad_30)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_30MOB,
    ROUND(SUM(pw.bad_33)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_33MOB,
    ROUND(SUM(pw.bad_36)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_36MOB,
    ROUND(SUM(pw.bad_39)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_39MOB,
    ROUND(SUM(pw.bad_42)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_42MOB,
    ROUND(SUM(pw.bad_45)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_45MOB,
    ROUND(SUM(pw.bad_48)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_48MOB,
    ROUND(SUM(pw.bad_51)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_51MOB,
    ROUND(SUM(pw.bad_54)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_54MOB,
    ROUND(SUM(pw.bad_57)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_57MOB,
    ROUND(SUM(pw.bad_60)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_60MOB,
    ROUND(SUM(pw.bad_63)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_63MOB,
    ROUND(SUM(pw.bad_66)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_66MOB,
    ROUND(SUM(pw.bad_69)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_69MOB,
    ROUND(SUM(pw.bad_72)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_72MOB,
    ROUND(SUM(pw.bad_75)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_75MOB,
    ROUND(SUM(pw.bad_78)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_78MOB,
    ROUND(SUM(pw.bad_81)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_81MOB,
    ROUND(SUM(pw.bad_84)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_84MOB,
    ROUND(SUM(pw.bad_87)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_87MOB,
    ROUND(SUM(pw.bad_90)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_90MOB,
    ROUND(SUM(pw.bad_93)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_93MOB,
    ROUND(SUM(pw.bad_96)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_96MOB,
    ROUND(SUM(pw.bad_99)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_99MOB,
    ROUND(SUM(pw.bad_102)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_102MOB,
    ROUND(SUM(pw.bad_105)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_105MOB,
    ROUND(SUM(pw.bad_108)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_108MOB,
    ROUND(SUM(pw.bad_111)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_111MOB,
    ROUND(SUM(pw.bad_114)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_114MOB,
    ROUND(SUM(pw.bad_117)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_117MOB,
    ROUND(SUM(pw.bad_120)/1e7, 6)  AS AMT_90PLUS_SETTLEMENT_120MOB,
    ROUND(SUM(pw.tpos_0)/1e7, 6) AS TPOS_0MOB,
    ROUND(SUM(pw.tpos_3)/1e7, 6) AS TPOS_3MOB,
    ROUND(SUM(pw.tpos_6)/1e7, 6) AS TPOS_6MOB,
    ROUND(SUM(pw.tpos_9)/1e7, 6) AS TPOS_9MOB,
    ROUND(SUM(pw.tpos_12)/1e7, 6) AS TPOS_12MOB,
    ROUND(SUM(pw.tpos_15)/1e7, 6) AS TPOS_15MOB,
    ROUND(SUM(pw.tpos_18)/1e7, 6) AS TPOS_18MOB,
    ROUND(SUM(pw.tpos_21)/1e7, 6) AS TPOS_21MOB,
    ROUND(SUM(pw.tpos_24)/1e7, 6) AS TPOS_24MOB,
    ROUND(SUM(pw.tpos_27)/1e7, 6) AS TPOS_27MOB,
    ROUND(SUM(pw.tpos_30)/1e7, 6) AS TPOS_30MOB,
    ROUND(SUM(pw.tpos_33)/1e7, 6) AS TPOS_33MOB,
    ROUND(SUM(pw.tpos_36)/1e7, 6) AS TPOS_36MOB,
    ROUND(SUM(pw.tpos_39)/1e7, 6) AS TPOS_39MOB,
    ROUND(SUM(pw.tpos_42)/1e7, 6) AS TPOS_42MOB,
    ROUND(SUM(pw.tpos_45)/1e7, 6) AS TPOS_45MOB,
    ROUND(SUM(pw.tpos_48)/1e7, 6) AS TPOS_48MOB,
    ROUND(SUM(pw.tpos_51)/1e7, 6) AS TPOS_51MOB,
    ROUND(SUM(pw.tpos_54)/1e7, 6) AS TPOS_54MOB,
    ROUND(SUM(pw.tpos_57)/1e7, 6) AS TPOS_57MOB,
    ROUND(SUM(pw.tpos_60)/1e7, 6) AS TPOS_60MOB,
    ROUND(SUM(pw.tpos_63)/1e7, 6) AS TPOS_63MOB,
    ROUND(SUM(pw.tpos_66)/1e7, 6) AS TPOS_66MOB,
    ROUND(SUM(pw.tpos_69)/1e7, 6) AS TPOS_69MOB,
    ROUND(SUM(pw.tpos_72)/1e7, 6) AS TPOS_72MOB,
    ROUND(SUM(pw.tpos_75)/1e7, 6) AS TPOS_75MOB,
    ROUND(SUM(pw.tpos_78)/1e7, 6) AS TPOS_78MOB,
    ROUND(SUM(pw.tpos_81)/1e7, 6) AS TPOS_81MOB,
    ROUND(SUM(pw.tpos_84)/1e7, 6) AS TPOS_84MOB,
    ROUND(SUM(pw.tpos_87)/1e7, 6) AS TPOS_87MOB,
    ROUND(SUM(pw.tpos_90)/1e7, 6) AS TPOS_90MOB,
    ROUND(SUM(pw.tpos_93)/1e7, 6) AS TPOS_93MOB,
    ROUND(SUM(pw.tpos_96)/1e7, 6) AS TPOS_96MOB,
    ROUND(SUM(pw.tpos_99)/1e7, 6) AS TPOS_99MOB,
    ROUND(SUM(pw.tpos_102)/1e7, 6) AS TPOS_102MOB,
    ROUND(SUM(pw.tpos_105)/1e7, 6) AS TPOS_105MOB,
    ROUND(SUM(pw.tpos_108)/1e7, 6) AS TPOS_108MOB,
    ROUND(SUM(pw.tpos_111)/1e7, 6) AS TPOS_111MOB,
    ROUND(SUM(pw.tpos_114)/1e7, 6) AS TPOS_114MOB,
    ROUND(SUM(pw.tpos_117)/1e7, 6) AS TPOS_117MOB,
    ROUND(SUM(pw.tpos_120)/1e7, 6) AS TPOS_120MOB
FROM base_fy b
LEFT JOIN perf_wide pw ON b.distinct_loan_no = pw.distinct_loan_no
GROUP BY b.fy_quarter, b.segment
ORDER BY substr(fy_quarter,3,2), substr(fy_quarter,7,1), b.segment;